# Generated by Django 4.1.4 on 2022-12-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('title', models.CharField(max_length=80)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
